
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     代码由模板根据数据库表结构自动生成，手动修改会被覆盖
	//
	//     
	// </auto-generated>
	//------------------------------------------------------------------------------
    
	using System;
	namespace NPocoDemo.Model 
	{
        /// <summary>
        /// 数据表实体类：User1 
        /// </summary>
        public class User1
        {    
		                 
			/// <summary>
			/// Int32:
			/// </summary>                       
			public Int32 Id {get;set;}   
                         
			/// <summary>
			/// String:
			/// </summary>                       
			public String Name {get;set;}   
                         
			/// <summary>
			/// String:
			/// </summary>                       
			public String LoginCode {get;set;}   
                         
			/// <summary>
			/// String:
			/// </summary>                       
			public String Password {get;set;}   
               
        }    
     }

	